package com.xiaomuedu.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLinkDictionary<M extends BaseLinkDictionary<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setLinkType(java.lang.String linkType) {
		set("linkType", linkType);
	}

	public java.lang.String getLinkType() {
		return get("linkType");
	}

	public void setDictionaryId(java.lang.Integer dictionaryId) {
		set("dictionaryId", dictionaryId);
	}

	public java.lang.Integer getDictionaryId() {
		return get("dictionaryId");
	}

	public void setLinkId(java.lang.Integer linkId) {
		set("linkId", linkId);
	}

	public java.lang.Integer getLinkId() {
		return get("linkId");
	}

}
