package com.xiaomuedu.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("dictionary", "id", Dictionary.class);
		arp.addMapping("figure", "id", Figure.class);
		arp.addMapping("figure_project", "id", FigureProject.class);
		arp.addMapping("friend_link", "id", FriendLink.class);
		arp.addMapping("invset_organ", "id", InvsetOrgan.class);
		arp.addMapping("link_dictionary", "id", LinkDictionary.class);
		arp.addMapping("project", "id", Project.class);
		arp.addMapping("user", "id", User.class);
	}
}

