package com.xiaomuedu.common.model;

import com.xiaomuedu.common.model.base.BaseFigure;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Figure extends BaseFigure<Figure> {
	public static final Figure dao = new Figure().dao();
}
