package com.xiaomuedu.common.model;

import com.xiaomuedu.common.model.base.BaseFigureProject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FigureProject extends BaseFigureProject<FigureProject> {
	public static final FigureProject dao = new FigureProject().dao();
}
