package com.xiaomuedu.common.model;

import com.xiaomuedu.common.model.base.BaseInvsetOrgan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvsetOrgan extends BaseInvsetOrgan<InvsetOrgan> {
	public static final InvsetOrgan dao = new InvsetOrgan().dao();
}
