package com.xiaomuedu.common.model;

import com.xiaomuedu.common.model.base.BaseLinkDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LinkDictionary extends BaseLinkDictionary<LinkDictionary> {
	public static final LinkDictionary dao = new LinkDictionary().dao();
}
